### PR TITLE
Add an "App(s) only" distribution set

### PR DESCRIPTION
**Pull request by chombourger**
Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>

### CODE REVIEW

**Comment by chombourger** [comment]
Hi @kaizimmerm 
I unfortunately ended up with the same circle-ci failure:
[WARNING] Missing header in: /home/ubuntu/hawkbit/hawkbit-runtime/hawkbit-update-server/docker/0.2.0M4-mysql/docker-compose.yml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hawkBit :: Parent .................................. SUCCESS [  7.037 s]
[INFO] hawkBit :: Core .................................... SUCCESS [  8.319 s]
[INFO] hawkBit :: Core Security ........................... SUCCESS [  5.397 s]
[INFO] hawkBit :: Repository .............................. SUCCESS [  0.139 s]
[INFO] hawkBit :: Repository :: API ....................... SUCCESS [  8.878 s]
[INFO] hawkBit :: Repository :: Core Implementation Support SUCCESS [  6.040 s]
[INFO] hawkBit :: Artifact Repository :: Filesystem ....... SUCCESS [  4.221 s]
[INFO] hawkBit :: Repository :: Test Utilities ............ SUCCESS [  0.515 s]
[INFO] hawkBit :: Repository :: JPA Implementation ........ SUCCESS [09:21 min]
[INFO] hawkBit :: REST Core ............................... SUCCESS [  6.255 s]
[INFO] hawkBit :: Mgmt REST API ........................... SUCCESS [  3.376 s]
[INFO] hawkBit :: Security Integration .................... SUCCESS [  4.648 s]
[INFO] hawkBit :: HTTP Security ........................... SUCCESS [  4.559 s]
[INFO] hawkBit :: REST Mgmt Resources ..................... SUCCESS [04:37 min]
[INFO] hawkBit :: DDI API ................................. SUCCESS [  0.385 s]
[INFO] hawkBit :: DDI Resources ........................... SUCCESS [03:29 min]
[INFO] hawkBit :: DMF ..................................... SUCCESS [  0.041 s]
[INFO] hawkBit :: DMF :: API .............................. SUCCESS [  0.037 s]
[INFO] hawkBit :: DMF :: RabbitMq Test module ............. SUCCESS [  0.095 s]
[INFO] hawkBit :: DMF :: AMQP 0.9 Implementation .......... SUCCESS [02:51 min]
[INFO] hawkBit :: Mgmt UI ................................. SUCCESS [01:01 min]
[INFO] hawkBit :: Spring Boot Autoconfigure ............... SUCCESS [  0.645 s]
[INFO] hawkBit :: Test Report ............................. SUCCESS [  0.092 s]
[INFO] hawkBit :: Spring Boot Starters .................... SUCCESS [  0.047 s]
[INFO] hawkBit :: Spring Boot Starter DDI API ............. SUCCESS [  0.232 s]
[INFO] hawkBit :: Spring Boot Starter DMF API ............. SUCCESS [  0.071 s]
[INFO] hawkBit :: Spring Boot Starter Management API ...... SUCCESS [  0.154 s]
[INFO] hawkBit :: Spring Boot Starter Management UI ....... SUCCESS [  0.067 s]
[INFO] hawkBit :: Spring Boot Starter ..................... SUCCESS [  0.336 s]
[INFO] hawkBit :: Runtime ................................. SUCCESS [  0.034 s]
[INFO] hawkBit :: Runtime :: Update Server ................ FAILURE [  1.215 s]

**Comment by chombourger** [comment]
I probably misunderstood how circle-ci works. I have rebased on top of master and it looks circle-ci was restarted (good). Let's see if the failures I had are now resolved

**Comment by michahirsch** [comment]
@chombourger yes, you don't need to create a new pull-request to trigger circle-ci. A new commit would also trigger circle-ci.

**Comment by chombourger** [comment]
thanks (and sorry for spamming the PR queue)

**Comment by kaizimmerm** [comment]
No worries. But I admit I was confused why my comments keep disappearing :)

**Pull request merged**
