### PR TITLE
Remove unused methods

### PR DESCRIPTION
**Pull request by kaizimmerm**
* Remove ununsed methods.
* Fixed Sonar issues
* Improved stream handling

### CODE REVIEW

**Comment by kaizimmerm** [comment]
@michahirsch please give me +1 for this request

**Comment by michahirsch** [comment]
the formatting changes, e.g. the extra space in the javadoc comment is this correct?

**Comment by kaizimmerm** [comment]
whitespace removal is correct. The master is wrong here. The problem is that there way to fix this on master for all files as IDE->Source->Format does not remove those whitespace.

**Comment by michahirsch** [comment]
Ok then everything ok, +1 will merge

**Pull request merged**
