### PR TITLE
Create Unit Test for all filter enum fields

### PR DESCRIPTION
**Pull request by SirWayne**
Create Unit tests for the new operation and filter fields in RSQL search query language:

Signed-off-by: SirWayne <dennis.melzer@bosch-si.com>

### CODE REVIEW

**Comment by kaizimmerm** [comment]
Please fix the merge conflicts first.

**Comment by kaizimmerm** [comment]
@michahirsch any comments?

**Comment by michahirsch** [comment]
As I can see the tests only verifying the count of the result of the RSQL query language. I'm not sure if this is totally sufficient. The count might be correct but the actual content of the result could be wrong. 

Maybe we could add like when we are searching e.g. for action with a specific status that the actions in the result only containing this status?

What you think?

**Comment by SirWayne** [comment]
Yes that is right, that could be extend as well as a combination of different operators, but this tests should first check the enum search fields.If someone adjusts the entity model that immediately notice, that the search query is broken e.g. ipAdress.

**Comment by michahirsch** [comment]
@kaizimmerm  then I would merge these tests as it is. This covers already more than we have now and we can extend them step by step. The pull-request already have 855 additions.
Thanks

**Pull request merged**
