### PR TITLE
Fix consistent context menu on tables

### PR DESCRIPTION
**Pull request by SirWayne**
1. Remove context menue on rollout grid and action history tree able and add a action column for all available actions.
2. Add possiblity to enable/disable html buttons in a grid table cell (**rebuild widgetset is necessary!!!**)

action_history_table

rollouts_grid

### CODE REVIEW

**Comment by michahirsch** [comment]
Do you might have an screenshot how it's looking now in the UI for the `ActionHistory` and `Rollout` Table/Grid ? Thx. Code looks good.

**Comment by kaizimmerm** [comment]
Can you please solve the merge conflicts?

**Comment by kaizimmerm** [comment]
Two comments.

1) At least on my safari the icon sizes in rollouts view are kind of messed up (action history looks good though)

screen shot 2016-07-15 at 09 08 08

2) I would say that soft->force switch should not be enabled for actions that are in canceling state. Makes functionally speaking no real sense.:

screen shot 2016-07-15 at 09 08 27

**Comment by melanieretter** [comment]
The Actions column looks like this now: 
forced_disabled

**Comment by melanieretter** [comment]
I improved the action icons in the rollout view:
rollout_actions

**Pull request merged**
