### PR TITLE
OpenID Connect support

### PR DESCRIPTION
**Pull request by BrandonSchmitt**
This pull request adds support for authentication providers implenting the [OpenID Connect](https://openid.net/connect/) interface. It uses the Spring Security 5 features for OAuth2 respectively OpenID Connect.

The default configuration has not changed, thus the single user/tenant with basic auth is still the default method.

### CODE REVIEW

**Comment by schabdo** [comment]
@hawkbit-bot verify please

**Comment by schabdo** [comment]
Thanks a lot for your contribution! OpenID connect support is highly appreciated in hawkBit. In order to fix the licence issue in the build just add a new licence-header file for your company [here](https://github.com/eclipse/hawkbit/tree/master/licenses). The content provided first in `OidcUserManagementAutoConfiguration.java` was totally correct:

```
/**
 * Copyright (c) 2019 Kiwigrid GmbH and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
```
You deserve credit for your contribution in hawkBit for sure :wink:

I’ll wrap my head around your PR and provide feedback. I assume testing this will take me quite a while

**Comment by BrandonSchmitt** [comment]
Thank you for your reply and the hint for the license.

I have resolved most SonarQube issues but the extra one:
`SecurityManagedConfiguration.java#L612: Define a constant instead of duplicating this literal "/UI/logout" 3 times.`
In my opinion, exactly following this advice and extracting this literal into a constant would result in inconsistencies in regard to the other literals like `"/UI/login/**"` in that function.
What is your opinion on this?

**Comment by schabdo** [comment]
> In my opinion, exactly following this advice and extracting this literal into a constant would result in inconsistencies in regard to the other literals like `"/UI/login/**"` in that function

It's just static code analysis and general speaking a good advice. But in this case I totally agree. I'd prefer to see secured URL pattern right away instead of generic constant name. Furthermore changing the constant value later on might have unintended security side-effects. So long story short: No need to fix that

**Comment by schabdo** [comment]
@hawkbit-bot verify please

**Comment by schabdo** [comment]
Busy times in hawkBit ... but I made some progress and finished the paperwork for the Eclipse IP team

**Comment by schabdo** [comment]
@BrandonSchmitt sorry, got distracted will work on it soon

**Comment by Informatic** [comment]
Don't want to nag everyone, but this seems like a great addition to hawkbit. Is this going to be merged anytime soon? :)

**Comment by schabdo** [comment]
ECA valid and in place (checked manually). Thanks a lot @BrandonSchmitt for your patience!

**Comment by axdotl** [comment]
Thanks for getting this merged.
Do you've information when one can expect an updated docker image?

**Comment by schabdo** [comment]
Building a new milestone will be my next task. This will include updated docker image as well. Expect to see it by end of next week

**Pull request merged**
