### PR TITLE
Quota for ActionStatus push to be checked only for intermediate statu…

### PR DESCRIPTION
**Pull request by vasilchev**
…ses. Always allow terminate/final status

### CODE REVIEW

**Comment by avgustinmm** [comment]
I'm not sure if it is a good idea. This way device could bypass limit and create unlimited statuses.
Anyway, if the device has reached the limit, something shall be done to clean up the action statuses.
If we allow action to be closed - what next? We next update will start and device again will be unable to report ..

**Comment by vasilchev** [comment]
> I'm not sure if it is a good idea. This way device could bypass limit and create unlimited statuses. Anyway, if the device has reached the limit, something shall be done to clean up the action statuses. If we allow action to be closed - what next? We next update will start and device again will be unable to report ..

There is an initial check whenever status comes if action is still active (meaning no final status yet reported)

Once reported final status - no further statuses intermediate/final could be reported

**Comment by avgustinmm** [comment]
> > I'm not sure if it is a good idea. This way device could bypass limit and create unlimited statuses. Anyway, if the device has reached the limit, something shall be done to clean up the action statuses. If we allow action to be closed - what next? We next update will start and device again will be unable to report ..
> 
> There is an initial check whenever status comes if action is still active (meaning no final status yet reported)
> 
> Once reported final status - no further statuses intermediate/final could be reported.
> 
> Behavior of device is indeed unpredictable, but we should accept final status so that action can be reported as completed, otherwise we miss the final status and action is in pending state until manual close (even though action has completed, we just reject the final status)

yes, but this won't percent new action and device could user only final statuses. And if it use intermediate - next action will be broken and hang again. So, this won't fix the problem - device has too many action statuses - they shall be clean up

**Comment by avgustinmm** [comment]
aha, if the quota is per action - then should be ok, if you add a check that the action statuses won't become more than quota + 1 or if it is carefully checked than in all flows someone has already checks the action is active (as you said).
Otherwise, again the device could create too many statuses (finished).
Note: even if you have checked that all flows check that action is finished - it's good to add quote + 1 check because in future new flows could be added or existing flows could be changed

**Review by avgustinmm — APPROVED** [review]

**Pull request merged**
