### PR TITLE
 Added Document attribute length constraint #1083

### PR DESCRIPTION
**Pull request by Fragnite-hub**
Updated the documentation , added the maximum constraint in key and value size #1083

### CODE REVIEW

**Comment by Fragnite-hub** [comment]
could you tell me the issue as in why the test cases are not passed since this is my first contribution .

**Comment by Fragnite-hub** [comment]
hi admins can you look at my PR.

**Comment by avgustinmm** [comment]
Thanks for the PR. 
However, I don't see the value this commit brings.
 
The actual value of the constants is part of the documentation anyway - the value of the CONTROLLER_ATTRIBUTE_VALUE_SIZE is documented at constant-values.html#org.eclipse.hawkbit.repository.model.Target.CONTROLLER_ATTRIBUTE_VALUE_SIZE. There is a fine way for checking the constant's value in javadoc out of the box.

I see few problems with this PR:
* document something that already is in the documentation - no need for PR
* if the constant value is changed someone shall take care to modify comment also - break's single point of truth 
* in the same class some constants has value mentioned in the field description, some not - lack of consistency

**Comment by Fragnite-hub** [comment]
So what we have to do to resolve #1083 . We can't just leave an issue open

**Comment by avgustinmm** [comment]
I suppose the proposal of #1083 was to add these constraints in the hawkbit website documentation. Where, the DDI API is documented - not in the javadoc.
Otherwise, if the proposal is for adding just javadoc comments I would close it with the same argumentation as for this PR

**Pull request closed without merging**
