### PR TITLE
README.md: Add RAUC hawkBit Client to list of clients supporting hawkBit

### PR DESCRIPTION
**Pull request by ejoerns**
Hey, we've created a simple python-based client interfacing between the RAUC updater's D-Bus interface on one side and the hawkBit DDI REST API on the other side.

If you're interested in seeing in seeing it working, it is the core of our updating demo shown here:
https://www.youtube.com/watch?v=SLX0Fd_y6Cc

### CODE REVIEW

**Comment by stefferber** [comment]
Cool ;-)

**Comment by kaizimmerm** [comment]
hanks for the contribution but I think you have not signed the eclipse ECA yet.

**Comment by ejoerns** [comment]
I've already signed it (shortly after submitting). The check reflects the state when submitting the patch, not the current one, please re-check ;)

**Comment by kaizimmerm** [comment]
ECA confirmed. Thanks for the contribution.

**Pull request merged**
