### PR TITLE
Add an "App(s) only" distribution set

### PR DESCRIPTION
**Pull request by chombourger**
Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>

### CODE REVIEW

**Comment by kaizimmerm** [comment]
Hi, thanks for the contribution. 

Sry about the circle compilation problem. We will see to fix this on master.

Please sign the ECA and let me know when its done.

Thanks,
Kai

**Comment by chombourger** [comment]
Hello @kaizimmerm ,

I have signed the ECA last Saturday (after I realize it was required) and checked that my e-mail address is now passing the ECA check. Let me know if something else needs to be done.

**Comment by kaizimmerm** [comment]
Hi @chombourger ,

I fixed the failed license check on master. Could you do me the favour and merge with master again? So we can see that the build is green.

Thanks,
kai

**Comment by chombourger** [comment]
Meaning closing this PR and creating a new one, right? Or is there another way?

**Pull request closed without merging**
